### ISSUE TITLE
Saving the model

### ISSUE THREAD

**Issue by Hi-Zed** [kdkalvik/ST-GCN#2]
Hi,
thanks a lot for your work. I am very new to TensorFlow and deep learning in general.
I managed to run your implementation on Google Cloud and obtained satisfying results.
However, I would like to save the model to use it on a different platform, unfortunately, when I add `tf.saved_model.save` (or similar) in the code I get an error I cannot understand.
This is the traceback:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 548, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 548, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/util/compat.py", line 87, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 239, in <module>
    tf.saved_model.save(model, '')
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 976, in save
    obj, export_dir, signatures, options, meta_graph_def)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 1047, in _build_meta_graph
    checkpoint_graph_view)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/saved_model/signature_serialization.py", line 75, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/saved_model/save.py", line 145, in list_functions
    self._serialization_cache)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2590, in _list_functions_for_serialization
    Model, self)._list_functions_for_serialization(serialization_cache)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 3019, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/base_serialization.py", line 87, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 79, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/model_serialization.py", line 51, in _get_serialized_attributes_internal
    default_signature = save_impl.default_save_signature(self.obj)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/saved_model/save_impl.py", line 205, in default_save_signature
    fn.get_concrete_function()
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1167, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 1073, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/saving/saving_utils.py", line 134, in _wrapped_model
    outputs = model(inputs, training=False)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)
  File "/home/gianluca_bardaro/ST-GCN/model/stgcn.py", line 169, in call
    x = self.data_bn(x, training=training)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/layers/normalization.py", line 752, in call
    scale, offset = _broadcast(self.gamma), _broadcast(self.beta)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/layers/normalization.py", line 749, in _broadcast
    return array_ops.reshape(v, broadcast_shape)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 195, in reshape
    result = gen_array_ops.reshape(tensor, shape, name)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8234, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 473, in _apply_op_helper
    raise err
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 470, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1499, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 338, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 264, in constant
    allow_broadcast=True)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 282, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 552, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [1, None, 1]. Consider casting elements to a supported type.
```
Is there any way to save the model in the `.pb` format?

Thanks in advance

**Comment by itskalvik** [comment]
The main [script ](https://github.com/kdkalvik/ST-GCN/blob/82d92a999ee91142647888db13b6c264f6fedc7c/main.py#L200)already saves the model weights. You are supposed to use [CheckpointManager ](https://www.tensorflow.org/api_docs/python/tf/train/CheckpointManager)to save the model.

**Comment by Hi-Zed** [comment]
Thanks for the answer.
I am aware that the main script saves checkpoints, however, I am trying to save the model as a `.pb` to use it with TensorFlow Lite.
Online I found that it is possible to convert a checkpoint to a SavedModel, but it requires a `.meta` file that is not created by your script.

**Comment by itskalvik** [comment]
I think you are just missing a filename. Instead of giving an empty string, try passing an arbitrary filename to save the model in.
